FROM almalinux:9
ENV course="DevOps with AWS" \
    trainer="sivakumar reddy" \
    duration="120HRS"

    # docker build -t env:1.0.0 .
    # docker run -d env:1.0.0  -- container will exit
    # docker run -d env:1.0.0 sleep 30 -- use sleep to stop the container exit
    
    # docker run -itd env:1.0.0 -- container will not exit
    # docker exec -it e01aceb bash
    # env   