FROM almalinux:9
#RUN dnf install ansible -y
RUN dnf install nginx -y



# docker build -t run:1.0.0 .
# docker run -d run:1.0.0 -- container will exit

# docker run -itd run:1.0.0 -- need to check
# docker ps