FROM almalinux:9
CMD ["ping","google.com"]

# CMD instruction can be overriden
# docker build -t entry:1.0.0 .
# docker run entry:1.0.0
# docker ps -a --no-trunc
# docker run entry:1.0.0 ping facebook.com
# docker ps -a --no-trunc
