FROM almalinux:9
ENV course="DevOps with AWS" \
    trainer="Rajasekhar reddy" \
    duration="120HRS"
RUN echo "Hello User: ${trainer}" > /tmp/devops.txt
CMD ["sleep", "100"]

# docker build -t arg:1.0.0  .
# docker run -d arg:1.0.0  .