FROM almalinux:9
RUN dnf install nginx -y
LABEL project="expense" \
      environment="dev" \
      component="frontend" \
      author="sivakumar"



# docker build -t label:1.0.0 .
# docker images -f "LABEL=project=expense"